### ISSUE TITLE
Unable to increase the size of the category images 

### ISSUE THREAD

**Issue by IamDhana** [arronhunt/react-native-emoji-selector#50]
![WhatsApp Image 2021-06-05 at 2 18 03 PM](https://user-images.githubusercontent.com/24955135/120885899-f22cea80-c608-11eb-96cb-b8dbf24ac81c.jpeg)

Unable to increase the size of the category images. Its very very small in real device.

Is there any way to adjust the size?

**Comment by arronhunt** [comment]
@IamDhana v1.0.0 (#49) should fix this problem and allow you to pass custom props to child components like the tabbar and tabs. I’m pushing out a beta release this week, stay tuned.

**Comment by soldatov-ss** [comment]
the issue still exist on version ^0.2.0
platform android
react-native v.0.72.8

**Comment by ml-arifshabab** [comment]
You can change emoji category tags sizes in following file.

```
<TouchableOpacity
          key={category.name}
          onPress={() => onPress(category)}
          style={{
            flex: 1,
            height: Platform.OS === "android" ?  tabSize + 20 : tabSize + 10, // change this for tab size.
            borderColor: category === activeCategory ? theme : "#EEEEEE",
            borderBottomWidth: 2,
            alignItems: "center",
            justifyContent: "center"
          }}
        >
          <Text
            style={{
              textAlign: "center",
              paddingBottom: 8,
              fontSize: Platform.OS === "android" ?  24 : 24 // change this for tab icon `size.`
            }}
          >
            {category.symbol}
          </Text>
```
